42ity/release-note

ipm/2.3.1.md

Add the missing release note for IPM 2.3.1

---

ipm/2.2.0.md
ipm/2.3.0.md
ipm/2.3.1.md
ipm/2.4.0.md

Fix formating and coherence

---

Makefile
tools/convert.sh

Builds on CI behaved differently than on local system, checking why...

Trace CI process of convert activity

---

ipm/2.4.0.md

Add note on Unix format for User Scripts

---

ipm/2.3.0-1.md
ipm/2.3.1-1.md

Add release notes for 2.3.0-1 / 2.3.1-1

---

ipm/2.5.0.md

Initial creation of IPM 2.5.0

---

ipm/2.4.0.md

Fix IPM 2.4.0 release date

---

ipm/2.4.0-1.md

Add entry for IPM2 2.4.0-1

---

ipm/2.4.0-1.md

Reword 2.4.0-1 information

---

tools/convert.sh

Add support for Cumulative PDF release note

---

ipm/2.5.0.md

Final release note for IPM2 2.5.0

---

ipm/2.6.0.md

Add entries for ESXi and Angular migration

---

ipm/2.6.0.md

Add UPS FW mass upgrade

---

tools/convert.sh

Add plain text output for Cumulative Release Note

---

ipm/2.5.0.md

Last minute amendment

---

ipm/2.6.0.md

New network management stack

---

ipm/2.6.0.md

Fix release month for 2.6.0

---

ipm/2.7.0.md

Add Fixes entries for IPM 2.7.0

---

ipm/2.7.0.md

Complete and rework IPM 2.7.0 release note

---

ipm/2.7.1.md

Dummy addition to test signature amendment.

---

ipm/2.7.1.md

Revert "Dummy addition to test signature amendment."
